name: Unittests Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pip wheel;
          pip install torch==${{ matrix.pytorch-version }};
          pip install -r requirements.txt;
#         pip install -r requirements/install.txt;
#         pip install -r requirements/install_async.txt;
#         pip install -r requirements/unittests.txt;
          pip install --no-deps .
      - name: Run Tests
        run: python -m pytest
