name: Unittests Linux

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pip wheel;
          pip install torch==${{ matrix.pytorch-version }};
          pip install -r requirements.txt;
#         pip install -r requirements/install.txt;
#         pip install -r requirements/install_async.txt;
#         pip install -r requirements/unittests.txt;
          pip install --no-deps .
      - name: Run Tests
        run: python -m pytest
